[profile.default]
retries = 0
jitter = true
status-level = "skip"
max-threads = 6

[test-groups]
serial = {max-threads = 1, backoff = "exponential", delay = "10", retries = 6 }
slow = {max-threads = 6, backoff = "exponential", delay = "10" }

[[profile.default.overrides]]
test-group = "serial"
filter = "test(networking::tests)"

[[profile.default.overrides]]
test-group = "slow"
filter = "test(file_io)"
